---
title: "Solar and Wind Energy Advancements"
subtitle: "Key drivers of the growth of solar and wind electricity generation in the USA."
date: "Aug 30, 2023"
categories: [Renewable, Data Viz]
bibliography: ../references.bib
---

## About

This project studies the driving effects of ***solar*** and ***wind*** energy advancements. It is a Master-level project for [EMSE 6572](https://eda.seas.gwu.edu) instructed by [Prof John Helveston](https://www.jhelvy.com).

<a href="https://rr.pingfanhu.com" class="btn btn-primary" role="button"> Access the Project </a>

## Project Overview

This project is performed as a team consisting of Pingfan Hu and Abbey Kollar.

Renewable energy in the USA has seen significant growth from 2000 to 2023. This research studies solar and wind energies and dives into three primary reasons behind this expansion:

1.  Cost of Solar and Wind Energy
2.  Policies and Incentives, and
3.  Energy Research Budgets

This project contains the following:

1.  Project Proposal
2.  Progress Report
3.  Final Report
4.  Presentation

The study aims to highlight which of these factors played the most crucial roles in this energy transformation. By understanding these relationships, we can better anticipate the future of renewable energy and make informed decisions.

Data wrangling and analysis are both performed using R coding language, presented with Quarto files.
