---
title: "BEV Smart Charging"
subtitle: "Quantifying the benefits and constraints of BEV Smart Charging adoption."
date: "Sept 07, 2023"
categories: [Smart Charging, Conjoint]
bibliography: ../references.bib
---

## About

This project builds a Conjoint Survey on BEV Smart Charging. It utilizes the [`cbctools`](https://jhelvy.github.io/cbcTools/) and [`logitr`](https://jhelvy.github.io/logitr/) packages developed by [Prof John Helveston](https://www.jhelvy.com).

<a href="https://sc.pingfanhu.com" class="btn btn-primary" role="button"> Showcase Website </a> <a href="https://sc.pingfanhu.com/pages/project_showcase.pdf" class="btn btn-primary" role="button"> Showcase PDF </a>

## Project Overview

This project is a combination of Master and PhD levels. The Master-level project is performed as a team with these members: Pingfan Hu, Bharath Ravindra, Sampada Dhakal, and Vedanth Surendra Hegde.

**Smart Charging** means to control and monitor the BEV charging process. In our project, it contains SMC and V2G. **SMC** is short for "Supplier-Managed Charging". It allows the charging stations to monitor, manage, and even restrict the charging process to optimize energy consumption. **V2G** is short for "Vehicle-to-Grid". It allows bidirectional charging, so that the vehicle can discharge a certain amount of electricity back to the grid to further optimize energy consumption by balancing supply and demand.

A previous study of @tarroja2021 has proved the economic feasibility of both SMC and V2G. This project is therefore a succeeding study of it.

The motivation of this study is described as below:

1.  The adoption of plug-in electric vehicles (BEVs) is essential for the U.S. to transition to a low-carbon energy system. However, if BEVs are charged during peak electricity demand hours, it could negate their environmental benefits and strain the electrical grid, necessitating expensive upgrades.
2.  SMC is a solution that aims to control the timing of BEV charging according to grid conditions. This strategy is particularly useful for BEV owners who leave their vehicles plugged in for extended periods, allowing the grid to intermittently charge the vehicles when it is most convenient for the grid.
3.  On the other hand, V2G is to charge the electricity from the BEVs back to the grid. It is a tougher objective compared with smart charging. This objective aims to decrease the amount of stationary power storage of the utility by better using the existing electricity in the BEVs.
4.  The challenge lies in convincing BEV owners to participate in the SMC and V2G programs. Concerns about privacy, the need for flexibility in their schedules, and lack of adequate compensation can deter participation.
5.  For our program to succeed, there's a need for a better understanding of social, behavioral, and economic factors influencing BEV owners' willingness to participate. Different regions, based on their BEV adoption and renewable energy levels, will have varying requirements for such programs.

In summary, the widespread adoption of BEVs is crucial for a sustainable future, but charging them during peak hours can have drawbacks. The Smart Charging programs could solve this issue, yet its success hinges on understanding and addressing BEV owners' concerns and varying regional needs.
